# Generated by Django 3.1.3 on 2021-06-01 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190228_0015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='chead0',
            new_name='subhead0',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='chead1',
            new_name='subhead1',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='chead2',
            new_name='subhead2',
        ),
    ]
